### PR TITLE
show more details of a multisig address in unlock hash (web) explorer

### LINKED ISSUE #157: the explorer should show more details of a multisig address
when showing the coin outputs of a multisig address like https://explorer.testnet.threefoldtoken.com/hash.html?hash=032aa4d45db439b02d00e26990369281c83da55c111c3a4cc8c43e951324d3794bd62ed7d909b2

You can not see it is a multisig  while the coin output itself  does show all details:
https://explorer.testnet.threefoldtoken.com/hash.html?hash=fdfd50902be19f73152f9ef62bb25b9da3c69179ce44d18c05f3c390796ad557

---

Originally posted @ https://github.com/rivine/rivine/issues/419

### PR DESCRIPTION
**Pull request by GlenDC**
closes #157

### CODE REVIEW

**Comment by GlenDC** [comment]
Rebased commit 654659319b64cd3befaf568897443b0be3f82016 into this. This commit added more information on hash page (e.g. total coins/blockstakes, locked coins/blockstakes, and last spend txn/block of coin/blockstake). Please review that commit as well when you get the change to do so @LeeSmet.

**Comment by GlenDC** [comment]
Also fixed some unreported bugs found in the web-explorer (frontend) code, while implementing commit 6546593 as well as this PR.

**Comment by GlenDC** [comment]
Confirmations property has been added to transaction/block statistics as well, so that you can see how many blocks are above it.

**Comment by GlenDC** [comment]
Going to merge this PR, but please do review this PR as well as commit 6546593 (rebased into this PR) when you get the chance @LeeSmet.

**Comment by LeeSmet** [comment]
seems good, lets see how this goes on testnet

**Pull request merged**
